version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dockerfile:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:mysql://db:3306/cooking_helper
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=cooking_helper
      - MYSQL_ROOT_PASSWORD=move_ToExplore*21
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local