INSERT INTO INGREDIENTS (ingredient_name, ingredient_description, ingredient_type, measurement_unit, calories, fat, carbohydrates, proteins)
VALUES
    ('Ground Beef', 'Lean ground beef', 'Meat', 'Ounce', 71, 5, 0, 6),
    ('Olive Oil', 'Extra virgin olive oil', 'Condiment', 'Tablespoon', 119, 13.5, 0, 0),
    ('Shrimp', 'Fresh shrimp', 'Seafood', 'Piece', 7, 0.1, 0.2, 1.4),
    ('Broccoli', 'Fresh broccoli', 'Vegetable', 'Cup', 55, 0.6, 11, 4.2),
    ('Cucumber', 'Fresh cucumber', 'Vegetable', 'Piece', 45, 0.3, 11, 2),
    ('Milk', 'Whole milk', 'Dairy', 'Cup', 146, 8, 13, 8),
    ('Tomato Sauce', 'Canned tomato sauce', 'Condiment', 'Cup', 74, 0.2, 17, 3.6),
    ('Grated Parmesan Cheese', 'Shredded Parmesan cheese', 'Dairy', 'Cup', 431, 28, 4, 38),
    ('Onion', 'Yellow onion', 'Vegetable', 'Piece', 44, 0.1, 10, 1.1),
    ('Garlic', 'Fresh garlic', 'Vegetable', 'Clove', 4, 0, 1, 0.2),
    ('Chicken Breasts', 'Boneless chicken breasts', 'Meat', 'Piece', 165, 3.6, 0, 31),
    ('Pizza Dough', 'Fresh pizza dough', 'Grain', 'Piece', 285, 4, 52, 9),
    ('Rice', 'White rice', 'Grain', 'Cup', 206, 0.4, 45, 4.3),
    ('Sliced Mushrooms', 'Fresh sliced mushrooms', 'Vegetable', 'Cup', 15, 0.2, 2, 2.2),
    ('Tomatoes', 'Fresh tomatoes', 'Vegetable', 'Piece', 22, 0.2, 5, 1.1),
    ('Cupcake Liners', 'Paper cupcake liners', 'Baking', 'Piece', 10, 0, 2, 0.2),
    ('Butter', 'Unsalted butter', 'Dairy', 'Cup', 1628, 184, 0.1, 2.4),
    ('Granulated Sugar', 'White granulated sugar', 'Sweetener', 'Cup', 774, 0, 200, 0),
    ('Brown Sugar', 'Light brown sugar', 'Sweetener', 'Cup', 836, 0, 218, 0),
    ('Eggs', 'Large eggs', 'Dairy', 'Piece', 72, 4.8, 0.6, 6),
    ('Vanilla Extract', 'Pure vanilla extract', 'Condiment', 'Teaspoon', 12, 0, 0.5, 0),
    ('All-Purpose Flour', 'White all-purpose flour', 'Grain', 'Cup', 455, 1.2, 95.4, 12.9);