INSERT INTO RECIPE (recipe_name, cooking_time, difficulty, cuisine, is_public, created_by)
VALUES ('Spaghetti Bolognese', 45, 'Medium', 'Italian', true, 1),
       ('Chicken Curry', 60, 'Medium', 'Indian', true, 2),
       ('Tacos', 30, 'Easy', 'Mexican', true, 3),
       ('Salad Nicoise', 15, 'Easy', 'French', false, 1),
       ('Sushi Rolls', 60, 'Hard', 'Japanese', true, 2),
       ('Hamburger', 20, 'Easy', 'American', true, 4),
       ('Pad Thai', 40, 'Medium', 'Thai', true, 3),
       ('Lasagna', 60, 'Hard', 'Italian', false, 1),
       ('Chicken Alfredo', 35, 'Medium', 'Italian', true, 5),
       ('Beef Stir-Fry', 25, 'Easy', 'Asian', true, 2),
       ('Miso Soup', 10, 'Easy', 'Japanese', true, 6),
       ('Goulash', 120, 'Hard', 'Hungarian', true, 7),
       ('Guacamole', 15, 'Easy', 'Mexican', true, 8),
       ('Ratatouille', 50, 'Medium', 'French', false, 9),
       ('Chicken Satay', 30, 'Medium', 'Thai', true, 10),
       ('Pancakes', 25, 'Easy', 'American', true, 5),
       ('Sushi Sashimi Combo', 60, 'Hard', 'Japanese', true, 11),
       ('Shrimp Scampi', 35, 'Medium', 'Italian', true, 12);
