INSERT INTO FOOD (food_name, description, type, measurement_unit, calories, fat, carbohydrates, proteins)
VALUES
    ('Spaghetti', 'Long, thin cylindrical pasta', 'Pasta', 'grams', 220, 1.1, 43, 8),
    ('Ground Beef', 'Minced meat from beef', 'Meat', 'grams', 250, 18, 0, 22),
    ('Tomato Sauce', 'Sauce made from tomatoes', 'Sauce', 'grams', 80, 0.5, 17, 3),
    ('Garlic', 'A pungent vegetable', 'Vegetable', 'cloves', 4, 0, 1, 0.2),
    ('Shrimp', 'Seafood with a delicate flavor', 'Seafood', 'grams', 84, 0.9, 0.2, 18),
    ('Butter', 'A dairy product made from milk', 'Dairy', 'grams', 717, 81, 0.1, 0.9),
    ('Mixed Vegetables', 'Assorted chopped vegetables', 'Vegetable', 'grams', 45, 0.3, 10, 2),
    ('Soy Sauce', 'A salty sauce made from soybeans', 'Sauce', 'milliliters', 8, 0, 2, 1),
    ('Chicken Breast', 'Lean meat from chicken', 'Meat', 'grams', 165, 3.6, 0, 31),
    ('Barbecue Sauce', 'A sweet and tangy sauce', 'Sauce', 'grams', 70, 0, 17, 0.6),
    ('Pizza Dough', 'A bread-like base for pizza', 'Bread', 'grams', 285, 4, 51, 9),
    ('Mozzarella Cheese', 'A soft, white cheese', 'Dairy', 'grams', 250, 18, 1, 22),
    ('Mushrooms', 'Edible fungi', 'Vegetable', 'grams', 15, 0.2, 2.3, 2.2),
    ('Arborio Rice', 'Short-grain rice', 'Grain', 'grams', 160, 0.5, 36, 3),
    ('Chicken Broth', 'A flavorful liquid made from chicken', 'Soup', 'milliliters', 7, 0.2, 0.4, 0.5),
    ('Lettuce', 'Leafy green vegetable', 'Vegetable', 'grams', 5, 0.1, 1, 0.5),
    ('Cucumber', 'A cylindrical green vegetable', 'Vegetable', 'grams', 16, 0.2, 3.6, 0.7),
    ('Tomato', 'Red, juicy fruit', 'Fruit', 'grams', 18, 0.2, 3.9, 0.9),
    ('Olive Oil', 'A liquid fat derived from olives', 'Oil', 'milliliters', 119, 13.5, 0, 0),
    ('Chocolate Chips', 'Small sweetened chocolate pieces', 'Baking', 'grams', 70, 4.5, 8, 0.7),
    ('Flour', 'A powder made from grains', 'Baking', 'grams', 364, 1.2, 76, 10),
    ('Sugar', 'A sweet crystalline substance', 'Sweetener', 'grams', 387, 0, 100, 0),
    ('Eggs', 'Bird eggs', 'Dairy', 'units', 72, 4.8, 0.6, 6),
    ('Baking Soda', 'A leavening agent', 'Baking', 'grams', 0, 0, 0, 0);
